export const BACKEND_URL = import.meta.env.VITE_BACKEND_FACSCIENCES;
export const BACKEND_PREINSCRIPTION_URL = import.meta.env
  .VITE_BACKEND_PREINSCRIPTION;
export const BACKEND_WEBSERVICES_URL = import.meta.env.VITE_BACKEND_WEBSERVICES;
