name: Build and Deploy Faculty of Science Website

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Docker image
        run: |
          docker build -t facscienceinterface:latest .

      - name: Save artifact
        run: |
          docker save facscienceinterface:latest | gzip > facscienceinterface_latest.tar.gz

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.DEPLOY_HOST }} >> ~/.ssh/known_hosts

      - name: Deploy to Server
        run: |
          scp facscienceinterface_latest.tar.gz ${{ secrets.DEPLOY_USER }}@${{ secrets.DEPLOY_HOST }}:/tmp/
          ssh ${{ secrets.DEPLOY_USER }}@${{ secrets.DEPLOY_HOST }} \
            "docker load < /tmp/facscienceinterface_latest.tar.gz && \
             docker rm -f facscienceinterface || true && \
             docker run -d --name facscienceinterface -p 9090:80 facscienceinterface:latest"
